twig:
    date:
        timezone: Europe/Paris
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    form_themes:
        - 'bootstrap_4_layout.html.twig'
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
    strict_variables: '%kernel.debug%'
